name: autograph_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^9.0.0
  salomon_bottom_bar: ^3.1.0
  animations: ^2.0.11
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.2
  provider: ^6.1.2
  sbp: ^0.1.0
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.3.4
  chewie: ^1.8.5
  video_player: ^2.9.2
  retrofit: ^4.4.0
  logger: ^2.4.0  # for logging purpose
  json_annotation: ^4.9.0
  flutter_windowmanager: ^0.2.0
  mesh_gradient: ^1.3.8
  screenshot_test:
    path: screenshot_test


dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^9.0.0
  google_nav_bar: ^5.0.7
  flutter_lints: ^4.0.0
  animated_icon: ^0.0.9
  retrofit_generator: ^9.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.8.0


flutter_native_splash:
  android: true

  ios: true
  web: false
  background_image: "assets/back_pr.png"

flutter:
  assets:
    - assets/

  uses-material-design: true
  fonts:
    - family: Inria Serif
      fonts:
        - asset: assets/fonts/InriaSerif-Regular.ttf

